# -*- coding: utf-8 -*-
"""APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ee9wjr-eDD88ks9sj3aUDzR_K8c7CxP5
"""

import streamlit as st
from PIL import Image

st.set_page_config(page_title="Influencer Discovery Tool", layout="wide")

# Title
st.markdown("""
    <h1 style='text-align: center; color: #4CAF50;'>🚀 Automated Influencer Discovery Tool</h1>
    <p style='text-align: center; font-size:18px;'>Find Instagram and YouTube influencers with ease</p>
""", unsafe_allow_html=True)

st.markdown("---")

# Load logos
col1, col2 = st.columns(2)

with col1:
    st.image("https://upload.wikimedia.org/wikipedia/commons/a/a5/Instagram_icon.png", width=80)
    st.markdown("""
        <h3 style='color:#E1306C;'>Instagram Influencers</h3>

    """, unsafe_allow_html=True)
    if st.button("🔍 Explore Instagram"):
        st.switch_page("instagram_page.py")

with col2:
    st.image("https://upload.wikimedia.org/wikipedia/commons/4/42/YouTube_icon_%282013-2017%29.png", width=80)
    st.markdown("""
        <h3 style='color:#FF0000;'>YouTube Influencers</h3>

    """, unsafe_allow_html=True)
    if st.button("📺 Explore YouTube"):
        st.switch_page("youtube_page.py")

st.markdown("---")
st.markdown("""
    <p style='text-align:center;'>Built with ❤️ using Streamlit</p>
""", unsafe_allow_html=True)