# -*- coding: utf-8 -*-
"""instagram_page.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZS4Bl2dv1sSAvPa4VZYu5uF8GNKlwq5t
"""

import streamlit as st
import pandas as pd

# Load Excel data
df = pd.read_excel("enhanced_influencers.xlsx")

# App Configuration
st.set_page_config(page_title="Instagram Influencer Finder", layout="wide")

# Logo and Title
st.markdown("""
    <div style='display: flex; align-items: center; gap: 10px; margin-bottom: 20px;'>
        <img src="https://upload.wikimedia.org/wikipedia/commons/a/a5/Instagram_icon.png" width="40">
        <h1 style='margin: 0;'>Instagram Influencer Finder</h1>
    </div>
""", unsafe_allow_html=True)

# Select category
categories = df["Category"].dropna().unique()
selected = st.selectbox("Select Influencer Type (e.g. Micro, Nano...)", sorted(categories))

# Filter and show results
filtered = df[df["Category"] == selected]

if not filtered.empty:
    st.markdown(f"### Found {len(filtered)} {selected} influencers:")
    for _, row in filtered.iterrows():
        st.markdown(f"""
            <div style='padding:15px; border:1px solid #eee; border-radius:12px; margin-bottom:15px;
                        box-shadow: 2px 2px 8px rgba(0,0,0,0.05); background-color: #fafafa;'>
                <img src="{row['Profile Image']}" width="60" style="border-radius:50%; float:left; margin-right:15px">
                <div style="overflow: hidden;">
                    <strong style='font-size: 1.1rem;'>{row['Username']}</strong><br>
                    👥 Followers: {row['Followers']}<br>
                    🔗 <a href="{row['Profile Link']}" target="_blank">View Profile</a>
                </div>
            </div>
        """, unsafe_allow_html=True)
else:
    st.warning("No influencers found for this category.")